--Tablas para los roles
CREATE TABLE ROLES (
    ID_ROL NUMBER NOT NULL,
    NOMBRE_ROL VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(150),
    ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL),
    CONSTRAINT UK_ROLES_NOMBRE UNIQUE (NOMBRE_ROL),
    CONSTRAINT CK_ROLES_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

--Secuencia para los roles
CREATE SEQUENCE SQ_ROLES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Tabla de usuarios
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER NOT NULL,
    ID_ROL NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ID_ROL)
        REFERENCES ROLES(ID_ROL),
    CONSTRAINT UK_USUARIOS_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_USUARIOS_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

--Con las 2 anteriores la relacion queda 1 ---- N usuarios


--Secuencia para los Usuarios
CREATE SEQUENCE SQ_USUARIOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Insertamos los roles iniciales
INSERT INTO ROLES (ID_ROL, NOMBRE_ROL, DESCRIPCION, ESTADO)
VALUES (SQ_ROLES.NEXTVAL, 'ADMINISTRADOR', 'Usuario con acceso completo al sistema', 'A');

INSERT INTO ROLES (ID_ROL, NOMBRE_ROL, DESCRIPCION, ESTADO)
VALUES (SQ_ROLES.NEXTVAL, 'VENDEDOR', 'Usuario encargado de registrar ventas y consultar inventario', 'A');

COMMIT;


--Revisar los roles
SELECT * FROM ROLES;


--Insertamos usuarios de prueba
INSERT INTO USUARIOS (ID_USUARIO, ID_ROL, NOMBRE, CORREO, PASSWORD, ESTADO)
VALUES (SQ_USUARIOS.NEXTVAL, 1, 'Administrador Principal', 'admin@inventario.com', '123456', 'A');

INSERT INTO USUARIOS (ID_USUARIO, ID_ROL, NOMBRE, CORREO, PASSWORD, ESTADO)
VALUES (SQ_USUARIOS.NEXTVAL, 2, 'Vendedor Principal', 'vendedor@inventario.com', '123456', 'A');

COMMIT;


--Revisamos los usurios con su rol
SELECT 
    U.ID_USUARIO,
    U.NOMBRE,
    U.CORREO,
    R.NOMBRE_ROL,
    U.ESTADO,
    U.FECHA_REGISTRO
FROM USUARIOS U
INNER JOIN ROLES R ON U.ID_ROL = R.ID_ROL;



--Las tablas base del inventario:

--Tabla de categorias
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(80) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT UK_CATEGORIAS_NOMBRE UNIQUE (NOMBRE_CATEGORIA),
    CONSTRAINT CK_CATEGORIAS_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

--Secuencia de categorias
CREATE SEQUENCE SQ_CATEGORIAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Tabla de proveedores
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR NUMBER NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100),
    DIRECCION VARCHAR2(200),
    ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT UK_PROVEEDORES_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_PROVEEDORES_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

--Secuencia de proveedores
CREATE SEQUENCE SQ_PROVEEDORES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Relaciones Proveedores 1 --- N productos

--Tabla de productos
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_PROVEEDOR NUMBER NOT NULL,
    NOMBRE_PRODUCTO VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(250),
    PRECIO_COMPRA NUMBER(10,2) NOT NULL,
    PRECIO_VENTA NUMBER(10,2) NOT NULL,
    STOCK NUMBER DEFAULT 0 NOT NULL,
    STOCK_MINIMO NUMBER DEFAULT 5 NOT NULL,
    ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT FK_PRODUCTOS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDORES(ID_PROVEEDOR),
    CONSTRAINT UK_PRODUCTOS_NOMBRE UNIQUE (NOMBRE_PRODUCTO),
    CONSTRAINT CK_PRODUCTOS_PRECIO_COMPRA CHECK (PRECIO_COMPRA >= 0),
    CONSTRAINT CK_PRODUCTOS_PRECIO_VENTA CHECK (PRECIO_VENTA >= 0),
    CONSTRAINT CK_PRODUCTOS_STOCK CHECK (STOCK >= 0),
    CONSTRAINT CK_PRODUCTOS_STOCK_MIN CHECK (STOCK_MINIMO >= 0),
    CONSTRAINT CK_PRODUCTOS_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

--Secuencia de productos
CREATE SEQUENCE SQ_PRODUCTOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



--Metemos datos de prueba

--Categorias:
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA, DESCRIPCION, ESTADO)
VALUES (SQ_CATEGORIAS.NEXTVAL, 'TECNOLOGIA', 'Productos electrónicos y accesorios tecnológicos', 'A');

INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA, DESCRIPCION, ESTADO)
VALUES (SQ_CATEGORIAS.NEXTVAL, 'OFICINA', 'Artículos de oficina y papelería', 'A');

COMMIT;

--Proveedores:
INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, TELEFONO, CORREO, DIRECCION, ESTADO)
VALUES (SQ_PROVEEDORES.NEXTVAL, 'Distribuidora Central', '2222-1111', 'central@proveedores.com', 'San José, Costa Rica', 'A');

INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, TELEFONO, CORREO, DIRECCION, ESTADO)
VALUES (SQ_PROVEEDORES.NEXTVAL, 'Proveedor Express', '8888-2222', 'express@proveedores.com', 'Heredia, Costa Rica', 'A');

COMMIT;

--Productos:
INSERT INTO PRODUCTOS (
    ID_PRODUCTO,
    ID_CATEGORIA,
    ID_PROVEEDOR,
    NOMBRE_PRODUCTO,
    DESCRIPCION,
    PRECIO_COMPRA,
    PRECIO_VENTA,
    STOCK,
    STOCK_MINIMO,
    ESTADO
)
VALUES (
    SQ_PRODUCTOS.NEXTVAL,
    1,
    1,
    'MOUSE INALAMBRICO',
    'Mouse inalámbrico USB',
    4500,
    7500,
    20,
    5,
    'A'
);

INSERT INTO PRODUCTOS (
    ID_PRODUCTO,
    ID_CATEGORIA,
    ID_PROVEEDOR,
    NOMBRE_PRODUCTO,
    DESCRIPCION,
    PRECIO_COMPRA,
    PRECIO_VENTA,
    STOCK,
    STOCK_MINIMO,
    ESTADO
)
VALUES (
    SQ_PRODUCTOS.NEXTVAL,
    2,
    2,
    'CUADERNO UNIVERSITARIO',
    'Cuaderno de 100 hojas',
    800,
    1500,
    50,
    10,
    'A'
);

COMMIT;

--Verificaciones:

SELECT * FROM CATEGORIAS;

SELECT * FROM PROVEEDORES;

SELECT 
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    C.NOMBRE_CATEGORIA,
    PR.NOMBRE_PROVEEDOR,
    P.PRECIO_COMPRA,
    P.PRECIO_VENTA,
    P.STOCK,
    P.STOCK_MINIMO,
    P.ESTADO
FROM PRODUCTOS P
INNER JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN PROVEEDORES PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR;




--Aca sigue la relacion VENTAS N:M PRODUCTOS cuando se crea DETALLE_VENTAS


--Creamos la tabla clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
    CEDULA VARCHAR2(30) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100),
    DIRECCION VARCHAR2(200),
    ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UK_CLIENTES_CEDULA UNIQUE (CEDULA),
    CONSTRAINT UK_CLIENTES_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_CLIENTES_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

--Secuencia de clientes
CREATE SEQUENCE SQ_CLIENTES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Tabla de ventas
CREATE TABLE VENTAS (
    ID_VENTA NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    FECHA_VENTA DATE DEFAULT SYSDATE NOT NULL,
    TOTAL NUMBER(10,2) DEFAULT 0 NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL,
    CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTA),
    CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_VENTAS_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT CK_VENTAS_TOTAL CHECK (TOTAL >= 0),
    CONSTRAINT CK_VENTAS_ESTADO CHECK (ESTADO IN ('REGISTRADA', 'ANULADA'))
);

--Secuencia de ventas
CREATE SEQUENCE SQ_VENTAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Tabla Detalle_ventas (Es la que conecta ventas con productos, Una venta puede tener varios productos, 
--y un producto puede aparecer en muchas ventas)

CREATE TABLE DETALLE_VENTAS (
    ID_DETALLE_VENTA NUMBER NOT NULL,
    ID_VENTA NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    SUBTOTAL NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_DETALLE_VENTAS PRIMARY KEY (ID_DETALLE_VENTA),
    CONSTRAINT FK_DETALLE_VENTAS_VENTAS FOREIGN KEY (ID_VENTA)
        REFERENCES VENTAS(ID_VENTA),
    CONSTRAINT FK_DETALLE_VENTAS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT CK_DETALLE_VENTAS_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DETALLE_VENTAS_PRECIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT CK_DETALLE_VENTAS_SUBTOTAL CHECK (SUBTOTAL >= 0)
);

--Secuencia de DETALLE_VENTAS
CREATE SEQUENCE SQ_DETALLE_VENTAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--Pruebas:

--Metemos Clientes de prueba:
INSERT INTO CLIENTES (
    ID_CLIENTE,
    NOMBRE_CLIENTE,
    CEDULA,
    TELEFONO,
    CORREO,
    DIRECCION,
    ESTADO
)
VALUES (
    SQ_CLIENTES.NEXTVAL,
    'Cliente General',
    '000000000',
    '2222-3333',
    'cliente@inventario.com',
    'San José, Costa Rica',
    'A'
);

INSERT INTO CLIENTES (
    ID_CLIENTE,
    NOMBRE_CLIENTE,
    CEDULA,
    TELEFONO,
    CORREO,
    DIRECCION,
    ESTADO
)
VALUES (
    SQ_CLIENTES.NEXTVAL,
    'María Rodríguez',
    '111111111',
    '8888-3333',
    'maria@correo.com',
    'Cartago, Costa Rica',
    'A'
);

COMMIT;

--verificar:
SELECT * FROM CLIENTES;


--Venta de prueba:
INSERT INTO VENTAS (
    ID_VENTA,
    ID_CLIENTE,
    ID_USUARIO,
    TOTAL,
    ESTADO
)
VALUES (
    SQ_VENTAS.NEXTVAL,
    1,
    2,
    0,
    'REGISTRADA'
);

COMMIT;

--Metemos detalle de la venta:
INSERT INTO DETALLE_VENTAS (
    ID_DETALLE_VENTA,
    ID_VENTA,
    ID_PRODUCTO,
    CANTIDAD,
    PRECIO_UNITARIO,
    SUBTOTAL
)
VALUES (
    SQ_DETALLE_VENTAS.NEXTVAL,
    1,
    1,
    2,
    7500,
    15000
);

INSERT INTO DETALLE_VENTAS (
    ID_DETALLE_VENTA,
    ID_VENTA,
    ID_PRODUCTO,
    CANTIDAD,
    PRECIO_UNITARIO,
    SUBTOTAL
)
VALUES (
    SQ_DETALLE_VENTAS.NEXTVAL,
    1,
    2,
    3,
    1500,
    4500
);

COMMIT;

--Actualizar total por ahora manual:
UPDATE VENTAS
SET TOTAL = (
    SELECT SUM(SUBTOTAL)
    FROM DETALLE_VENTAS
    WHERE ID_VENTA = 1
)
WHERE ID_VENTA = 1;

COMMIT;


--Verificar venta completa
SELECT
    V.ID_VENTA,
    C.NOMBRE_CLIENTE,
    U.NOMBRE AS VENDEDOR,
    V.FECHA_VENTA,
    P.NOMBRE_PRODUCTO,
    DV.CANTIDAD,
    DV.PRECIO_UNITARIO,
    DV.SUBTOTAL,
    V.TOTAL,
    V.ESTADO
FROM VENTAS V
INNER JOIN CLIENTES C ON V.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN USUARIOS U ON V.ID_USUARIO = U.ID_USUARIO
INNER JOIN DETALLE_VENTAS DV ON V.ID_VENTA = DV.ID_VENTA
INNER JOIN PRODUCTOS P ON DV.ID_PRODUCTO = P.ID_PRODUCTO
ORDER BY V.ID_VENTA;



--Sigue Tabla de compras y de detalle_compras

--Tabla Compras:
CREATE TABLE COMPRAS (
    ID_COMPRA NUMBER NOT NULL,
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    FECHA_COMPRA DATE DEFAULT SYSDATE NOT NULL,
    TOTAL NUMBER(10,2) DEFAULT 0 NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL,
    CONSTRAINT PK_COMPRAS PRIMARY KEY (ID_COMPRA),
    CONSTRAINT FK_COMPRAS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDORES(ID_PROVEEDOR),
    CONSTRAINT FK_COMPRAS_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT CK_COMPRAS_TOTAL CHECK (TOTAL >= 0),
    CONSTRAINT CK_COMPRAS_ESTADO CHECK (ESTADO IN ('REGISTRADA', 'ANULADA'))
);

--Secuencia compras:
CREATE SEQUENCE SQ_COMPRAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Tabla de detalle_compras:
CREATE TABLE DETALLE_COMPRAS (
    ID_DETALLE_COMPRA NUMBER NOT NULL,
    ID_COMPRA NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    SUBTOTAL NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_DETALLE_COMPRAS PRIMARY KEY (ID_DETALLE_COMPRA),
    CONSTRAINT FK_DETALLE_COMPRAS_COMPRAS FOREIGN KEY (ID_COMPRA)
        REFERENCES COMPRAS(ID_COMPRA),
    CONSTRAINT FK_DETALLE_COMPRAS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT CK_DETALLE_COMPRAS_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DETALLE_COMPRAS_PRECIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT CK_DETALLE_COMPRAS_SUBTOTAL CHECK (SUBTOTAL >= 0)
);

--Secuencia de detalle_compras:
CREATE SEQUENCE SQ_DETALLE_COMPRAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



--Mas pruebas:

--Simula compra
INSERT INTO COMPRAS (
    ID_COMPRA,
    ID_PROVEEDOR,
    ID_USUARIO,
    TOTAL,
    ESTADO
)
VALUES (
    SQ_COMPRAS.NEXTVAL,
    1,
    1,
    0,
    'REGISTRADA'
);

COMMIT;

INSERT INTO DETALLE_COMPRAS (
    ID_DETALLE_COMPRA,
    ID_COMPRA,
    ID_PRODUCTO,
    CANTIDAD,
    PRECIO_UNITARIO,
    SUBTOTAL
)
VALUES (
    SQ_DETALLE_COMPRAS.NEXTVAL,
    1,
    1,
    10,
    4500,
    45000
);

--Simular detalle compra
INSERT INTO DETALLE_COMPRAS (
    ID_DETALLE_COMPRA,
    ID_COMPRA,
    ID_PRODUCTO,
    CANTIDAD,
    PRECIO_UNITARIO,
    SUBTOTAL
)
VALUES (
    SQ_DETALLE_COMPRAS.NEXTVAL,
    1,
    2,
    20,
    800,
    16000
);

COMMIT;

--Actualizar Total de la compra
UPDATE COMPRAS
SET TOTAL = (
    SELECT SUM(SUBTOTAL)
    FROM DETALLE_COMPRAS
    WHERE ID_COMPRA = 1
)
WHERE ID_COMPRA = 1;

COMMIT;


--VERIFICAMOS COMPRA COMPLETA:
SELECT
    C.ID_COMPRA,
    PR.NOMBRE_PROVEEDOR,
    U.NOMBRE AS USUARIO_REGISTRA,
    C.FECHA_COMPRA,
    P.NOMBRE_PRODUCTO,
    DC.CANTIDAD,
    DC.PRECIO_UNITARIO,
    DC.SUBTOTAL,
    C.TOTAL,
    C.ESTADO
FROM COMPRAS C
INNER JOIN PROVEEDORES PR ON C.ID_PROVEEDOR = PR.ID_PROVEEDOR
INNER JOIN USUARIOS U ON C.ID_USUARIO = U.ID_USUARIO
INNER JOIN DETALLE_COMPRAS DC ON C.ID_COMPRA = DC.ID_COMPRA
INNER JOIN PRODUCTOS P ON DC.ID_PRODUCTO = P.ID_PRODUCTO
ORDER BY C.ID_COMPRA;




--Tablas de inventario

--Movimientos_inventario
CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID_MOVIMIENTO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    TIPO_MOVIMIENTO VARCHAR2(20) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    STOCK_ANTERIOR NUMBER NOT NULL,
    STOCK_NUEVO NUMBER NOT NULL,
    FECHA_MOVIMIENTO DATE DEFAULT SYSDATE NOT NULL,
    DESCRIPCION VARCHAR2(250),
    ID_COMPRA NUMBER,
    ID_VENTA NUMBER,
    CONSTRAINT PK_MOVIMIENTOS_INVENTARIO PRIMARY KEY (ID_MOVIMIENTO),
    CONSTRAINT FK_MOV_INV_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT FK_MOV_INV_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_MOV_INV_COMPRAS FOREIGN KEY (ID_COMPRA)
        REFERENCES COMPRAS(ID_COMPRA),
    CONSTRAINT FK_MOV_INV_VENTAS FOREIGN KEY (ID_VENTA)
        REFERENCES VENTAS(ID_VENTA),
    CONSTRAINT CK_MOV_INV_TIPO CHECK (TIPO_MOVIMIENTO IN ('ENTRADA', 'SALIDA', 'AJUSTE')),
    CONSTRAINT CK_MOV_INV_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_MOV_INV_STOCK_ANT CHECK (STOCK_ANTERIOR >= 0),
    CONSTRAINT CK_MOV_INV_STOCK_NUEVO CHECK (STOCK_NUEVO >= 0)
);

--Secuencia de movimientos_inventario
CREATE SEQUENCE SQ_MOVIMIENTOS_INVENTARIO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


--Sincronizar con lo de antes:
INSERT INTO MOVIMIENTOS_INVENTARIO (
    ID_MOVIMIENTO,
    ID_PRODUCTO,
    ID_USUARIO,
    TIPO_MOVIMIENTO,
    CANTIDAD,
    STOCK_ANTERIOR,
    STOCK_NUEVO,
    DESCRIPCION,
    ID_VENTA
)
SELECT
    SQ_MOVIMIENTOS_INVENTARIO.NEXTVAL,
    DV.ID_PRODUCTO,
    V.ID_USUARIO,
    'SALIDA',
    DV.CANTIDAD,
    P.STOCK,
    P.STOCK - DV.CANTIDAD,
    'Salida de inventario por venta de prueba',
    V.ID_VENTA
FROM DETALLE_VENTAS DV
INNER JOIN VENTAS V ON DV.ID_VENTA = V.ID_VENTA
INNER JOIN PRODUCTOS P ON DV.ID_PRODUCTO = P.ID_PRODUCTO
WHERE V.ID_VENTA = 1;

--Descontamos del stock
UPDATE PRODUCTOS P
SET P.STOCK = P.STOCK - (
    SELECT NVL(SUM(DV.CANTIDAD), 0)
    FROM DETALLE_VENTAS DV
    WHERE DV.ID_PRODUCTO = P.ID_PRODUCTO
    AND DV.ID_VENTA = 1
)
WHERE EXISTS (
    SELECT 1
    FROM DETALLE_VENTAS DV
    WHERE DV.ID_PRODUCTO = P.ID_PRODUCTO
    AND DV.ID_VENTA = 1
);

COMMIT;


--Luego se registra la entrada por compra:
INSERT INTO MOVIMIENTOS_INVENTARIO (
    ID_MOVIMIENTO,
    ID_PRODUCTO,
    ID_USUARIO,
    TIPO_MOVIMIENTO,
    CANTIDAD,
    STOCK_ANTERIOR,
    STOCK_NUEVO,
    DESCRIPCION,
    ID_COMPRA
)
SELECT
    SQ_MOVIMIENTOS_INVENTARIO.NEXTVAL,
    DC.ID_PRODUCTO,
    C.ID_USUARIO,
    'ENTRADA',
    DC.CANTIDAD,
    P.STOCK,
    P.STOCK + DC.CANTIDAD,
    'Entrada de inventario por compra de prueba',
    C.ID_COMPRA
FROM DETALLE_COMPRAS DC
INNER JOIN COMPRAS C ON DC.ID_COMPRA = C.ID_COMPRA
INNER JOIN PRODUCTOS P ON DC.ID_PRODUCTO = P.ID_PRODUCTO
WHERE C.ID_COMPRA = 1;

--Se aumenta el stock por esa compra
UPDATE PRODUCTOS P
SET P.STOCK = P.STOCK + (
    SELECT NVL(SUM(DC.CANTIDAD), 0)
    FROM DETALLE_COMPRAS DC
    WHERE DC.ID_PRODUCTO = P.ID_PRODUCTO
    AND DC.ID_COMPRA = 1
)
WHERE EXISTS (
    SELECT 1
    FROM DETALLE_COMPRAS DC
    WHERE DC.ID_PRODUCTO = P.ID_PRODUCTO
    AND DC.ID_COMPRA = 1
);

COMMIT;


--Revisiones:
--Verificar Stock
SELECT 
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK,
    STOCK_MINIMO
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;


--Verificar movimientos
SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.FECHA_MOVIMIENTO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;


--Siguen los triggers

--Trigger antes de insertar detalle de venta
--Este trigger hace 3 cosas:

--Busca el precio de venta actual del producto
--Verifica que haya stock suficiente
--Calcula automáticamente el subtotal

CREATE OR REPLACE TRIGGER TRG_BI_DETALLE_VENTAS
BEFORE INSERT ON DETALLE_VENTAS
FOR EACH ROW
DECLARE
    V_PRECIO_VENTA PRODUCTOS.PRECIO_VENTA%TYPE;
    V_STOCK PRODUCTOS.STOCK%TYPE;
BEGIN
    SELECT PRECIO_VENTA, STOCK
    INTO V_PRECIO_VENTA, V_STOCK
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    IF V_STOCK < :NEW.CANTIDAD THEN
        RAISE_APPLICATION_ERROR(-20001, 'No hay stock suficiente para realizar la venta.');
    END IF;

    :NEW.PRECIO_UNITARIO := V_PRECIO_VENTA;
    :NEW.SUBTOTAL := :NEW.CANTIDAD * V_PRECIO_VENTA;
END;
/

--Trigger después de insertar detalle de venta
--Este trigger hace:

--Descuenta el stock
--Registra la salida en MOVIMIENTOS_INVENTARIO
--Suma el subtotal al total de la venta

CREATE OR REPLACE TRIGGER TRG_AI_DETALLE_VENTAS
AFTER INSERT ON DETALLE_VENTAS
FOR EACH ROW
DECLARE
    V_STOCK_ANTERIOR PRODUCTOS.STOCK%TYPE;
    V_ID_USUARIO VENTAS.ID_USUARIO%TYPE;
BEGIN
    SELECT STOCK
    INTO V_STOCK_ANTERIOR
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    SELECT ID_USUARIO
    INTO V_ID_USUARIO
    FROM VENTAS
    WHERE ID_VENTA = :NEW.ID_VENTA;

    UPDATE PRODUCTOS
    SET STOCK = STOCK - :NEW.CANTIDAD
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    INSERT INTO MOVIMIENTOS_INVENTARIO (
        ID_MOVIMIENTO,
        ID_PRODUCTO,
        ID_USUARIO,
        TIPO_MOVIMIENTO,
        CANTIDAD,
        STOCK_ANTERIOR,
        STOCK_NUEVO,
        DESCRIPCION,
        ID_VENTA
    )
    VALUES (
        SQ_MOVIMIENTOS_INVENTARIO.NEXTVAL,
        :NEW.ID_PRODUCTO,
        V_ID_USUARIO,
        'SALIDA',
        :NEW.CANTIDAD,
        V_STOCK_ANTERIOR,
        V_STOCK_ANTERIOR - :NEW.CANTIDAD,
        'Salida automática por venta',
        :NEW.ID_VENTA
    );

    UPDATE VENTAS
    SET TOTAL = TOTAL + :NEW.SUBTOTAL
    WHERE ID_VENTA = :NEW.ID_VENTA;
END;
/



--Luego los triggers de compra:

--Trigger antes de insertar detalle de compra
--Este trigger calcula automáticamente el subtotal de una compra

--Si no mandamos precio unitario, usa el PRECIO_COMPRA del producto

CREATE OR REPLACE TRIGGER TRG_BI_DETALLE_COMPRAS
BEFORE INSERT ON DETALLE_COMPRAS
FOR EACH ROW
DECLARE
    V_PRECIO_COMPRA PRODUCTOS.PRECIO_COMPRA%TYPE;
BEGIN
    SELECT PRECIO_COMPRA
    INTO V_PRECIO_COMPRA
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    IF :NEW.PRECIO_UNITARIO IS NULL OR :NEW.PRECIO_UNITARIO = 0 THEN
        :NEW.PRECIO_UNITARIO := V_PRECIO_COMPRA;
    END IF;

    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;
/


--Trigger después de insertar detalle de compra
--Este trigger hace:

--Aumenta el stock
--Registra entrada en MOVIMIENTOS_INVENTARIO
--Suma el subtotal al total de la compra

CREATE OR REPLACE TRIGGER TRG_AI_DETALLE_COMPRAS
AFTER INSERT ON DETALLE_COMPRAS
FOR EACH ROW
DECLARE
    V_STOCK_ANTERIOR PRODUCTOS.STOCK%TYPE;
    V_ID_USUARIO COMPRAS.ID_USUARIO%TYPE;
BEGIN
    SELECT STOCK
    INTO V_STOCK_ANTERIOR
    FROM PRODUCTOS
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    SELECT ID_USUARIO
    INTO V_ID_USUARIO
    FROM COMPRAS
    WHERE ID_COMPRA = :NEW.ID_COMPRA;

    UPDATE PRODUCTOS
    SET STOCK = STOCK + :NEW.CANTIDAD
    WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    INSERT INTO MOVIMIENTOS_INVENTARIO (
        ID_MOVIMIENTO,
        ID_PRODUCTO,
        ID_USUARIO,
        TIPO_MOVIMIENTO,
        CANTIDAD,
        STOCK_ANTERIOR,
        STOCK_NUEVO,
        DESCRIPCION,
        ID_COMPRA
    )
    VALUES (
        SQ_MOVIMIENTOS_INVENTARIO.NEXTVAL,
        :NEW.ID_PRODUCTO,
        V_ID_USUARIO,
        'ENTRADA',
        :NEW.CANTIDAD,
        V_STOCK_ANTERIOR,
        V_STOCK_ANTERIOR + :NEW.CANTIDAD,
        'Entrada automática por compra',
        :NEW.ID_COMPRA
    );

    UPDATE COMPRAS
    SET TOTAL = TOTAL + :NEW.SUBTOTAL
    WHERE ID_COMPRA = :NEW.ID_COMPRA;
END;
/

--Verificamos los triggers de detalle ventas y detalles compra
SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_BI_DETALLE_VENTAS',
    'TRG_AI_DETALLE_VENTAS',
    'TRG_BI_DETALLE_COMPRAS',
    'TRG_AI_DETALLE_COMPRAS'
);


--Pruebas:

--Probar trigger de venta automática:
--Se crea nueva venta

INSERT INTO VENTAS (
    ID_VENTA,
    ID_CLIENTE,
    ID_USUARIO,
    TOTAL,
    ESTADO
)
VALUES (
    SQ_VENTAS.NEXTVAL,
    2,
    2,
    0,
    'REGISTRADA'
);

COMMIT;

--Se inserta el detalle
INSERT INTO DETALLE_VENTAS (
    ID_DETALLE_VENTA,
    ID_VENTA,
    ID_PRODUCTO,
    CANTIDAD
)
VALUES (
    SQ_DETALLE_VENTAS.NEXTVAL,
    2,
    1,
    1
);

COMMIT;

--Vender 1 Mouse inalámbrico
--Bajar el stock de 28 a 27
--Actualizar el total de la venta a 7500
--Registrar movimiento de SALIDA

--Verificamos la nueva venta y el stock y el movimiento del inventario:
SELECT
    V.ID_VENTA,
    C.NOMBRE_CLIENTE,
    U.NOMBRE AS VENDEDOR,
    V.TOTAL,
    V.ESTADO
FROM VENTAS V
INNER JOIN CLIENTES C ON V.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN USUARIOS U ON V.ID_USUARIO = U.ID_USUARIO
WHERE V.ID_VENTA = 2;

SELECT 
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;

SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;

--Probamos el trigger de compra automatica

INSERT INTO COMPRAS (
    ID_COMPRA,
    ID_PROVEEDOR,
    ID_USUARIO,
    TOTAL,
    ESTADO
)
VALUES (
    SQ_COMPRAS.NEXTVAL,
    2,
    1,
    0,
    'REGISTRADA'
);

INSERT INTO DETALLE_COMPRAS (
    ID_DETALLE_COMPRA,
    ID_COMPRA,
    ID_PRODUCTO,
    CANTIDAD,
    PRECIO_UNITARIO
)
VALUES (
    SQ_DETALLE_COMPRAS.NEXTVAL,
    SQ_COMPRAS.CURRVAL,
    2,
    5,
    800
);

COMMIT;


SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;




--CREAR LAS VISTAS DE REPORTES

--Vista general:
CREATE OR REPLACE VIEW VW_INVENTARIO_GENERAL AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    P.DESCRIPCION,
    C.NOMBRE_CATEGORIA,
    PR.NOMBRE_PROVEEDOR,
    P.PRECIO_COMPRA,
    P.PRECIO_VENTA,
    P.STOCK,
    P.STOCK_MINIMO,
    P.ESTADO,
    P.FECHA_REGISTRO
FROM PRODUCTOS P
INNER JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN PROVEEDORES PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR;

SELECT * FROM VW_INVENTARIO_GENERAL;


--Vista de productos con el stock bajo
CREATE OR REPLACE VIEW VW_PRODUCTOS_STOCK_BAJO AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    C.NOMBRE_CATEGORIA,
    PR.NOMBRE_PROVEEDOR,
    P.STOCK,
    P.STOCK_MINIMO,
    P.ESTADO
FROM PRODUCTOS P
INNER JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN PROVEEDORES PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
WHERE P.STOCK <= P.STOCK_MINIMO
AND P.ESTADO = 'A';

SELECT * FROM VW_PRODUCTOS_STOCK_BAJO;



--Vista de detalle de ventas
CREATE OR REPLACE VIEW VW_VENTAS_DETALLE AS
SELECT
    V.ID_VENTA,
    V.FECHA_VENTA,
    C.ID_CLIENTE,
    C.NOMBRE_CLIENTE,
    U.ID_USUARIO,
    U.NOMBRE AS VENDEDOR,
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    DV.CANTIDAD,
    DV.PRECIO_UNITARIO,
    DV.SUBTOTAL,
    V.TOTAL,
    V.ESTADO
FROM VENTAS V
INNER JOIN CLIENTES C ON V.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN USUARIOS U ON V.ID_USUARIO = U.ID_USUARIO
INNER JOIN DETALLE_VENTAS DV ON V.ID_VENTA = DV.ID_VENTA
INNER JOIN PRODUCTOS P ON DV.ID_PRODUCTO = P.ID_PRODUCTO;

SELECT * FROM VW_VENTAS_DETALLE
ORDER BY ID_VENTA;



--Vista de detalle de compras
CREATE OR REPLACE VIEW VW_COMPRAS_DETALLE AS
SELECT
    C.ID_COMPRA,
    C.FECHA_COMPRA,
    PR.ID_PROVEEDOR,
    PR.NOMBRE_PROVEEDOR,
    U.ID_USUARIO,
    U.NOMBRE AS USUARIO_REGISTRA,
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    DC.CANTIDAD,
    DC.PRECIO_UNITARIO,
    DC.SUBTOTAL,
    C.TOTAL,
    C.ESTADO
FROM COMPRAS C
INNER JOIN PROVEEDORES PR ON C.ID_PROVEEDOR = PR.ID_PROVEEDOR
INNER JOIN USUARIOS U ON C.ID_USUARIO = U.ID_USUARIO
INNER JOIN DETALLE_COMPRAS DC ON C.ID_COMPRA = DC.ID_COMPRA
INNER JOIN PRODUCTOS P ON DC.ID_PRODUCTO = P.ID_PRODUCTO;

SELECT * FROM VW_COMPRAS_DETALLE
ORDER BY ID_COMPRA;



--Vista de productos mas vendidos
CREATE OR REPLACE VIEW VW_PRODUCTOS_MAS_VENDIDOS AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    SUM(DV.CANTIDAD) AS TOTAL_UNIDADES_VENDIDAS,
    SUM(DV.SUBTOTAL) AS TOTAL_VENDIDO
FROM DETALLE_VENTAS DV
INNER JOIN PRODUCTOS P ON DV.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN VENTAS V ON DV.ID_VENTA = V.ID_VENTA
WHERE V.ESTADO = 'REGISTRADA'
GROUP BY
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO;
    
SELECT * FROM VW_PRODUCTOS_MAS_VENDIDOS
ORDER BY TOTAL_UNIDADES_VENDIDAS DESC;



--Vista de ventas por dia
CREATE OR REPLACE VIEW VW_VENTAS_POR_DIA AS
SELECT
    TRUNC(FECHA_VENTA) AS FECHA,
    COUNT(ID_VENTA) AS CANTIDAD_VENTAS,
    SUM(TOTAL) AS TOTAL_VENDIDO
FROM VENTAS
WHERE ESTADO = 'REGISTRADA'
GROUP BY TRUNC(FECHA_VENTA);

SELECT * FROM VW_VENTAS_POR_DIA
ORDER BY FECHA;



--Vista de movimientos de inventario
CREATE OR REPLACE VIEW VW_MOVIMIENTOS_INVENTARIO AS
SELECT
    M.ID_MOVIMIENTO,
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    U.ID_USUARIO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.FECHA_MOVIMIENTO,
    M.DESCRIPCION,
    M.ID_COMPRA,
    M.ID_VENTA
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO;

SELECT * FROM VW_MOVIMIENTOS_INVENTARIO
ORDER BY ID_MOVIMIENTO;

--Revisar que las vistas si existen:
SELECT VIEW_NAME
FROM USER_VIEWS
WHERE VIEW_NAME IN (
    'VW_INVENTARIO_GENERAL',
    'VW_PRODUCTOS_STOCK_BAJO',
    'VW_VENTAS_DETALLE',
    'VW_COMPRAS_DETALLE',
    'VW_PRODUCTOS_MAS_VENDIDOS',
    'VW_VENTAS_POR_DIA',
    'VW_MOVIMIENTOS_INVENTARIO'
)
ORDER BY VIEW_NAME;




--Creamos los procedimientos almacenados(SP):

--CATEGORIAS
--Procedimiento para insertar categoria
CREATE OR REPLACE PROCEDURE SP_INS_CATEGORIA (
    P_NOMBRE_CATEGORIA IN CATEGORIAS.NOMBRE_CATEGORIA%TYPE,
    P_DESCRIPCION IN CATEGORIAS.DESCRIPCION%TYPE
)
AS
BEGIN
    INSERT INTO CATEGORIAS (
        ID_CATEGORIA,
        NOMBRE_CATEGORIA,
        DESCRIPCION,
        ESTADO
    )
    VALUES (
        SQ_CATEGORIAS.NEXTVAL,
        P_NOMBRE_CATEGORIA,
        P_DESCRIPCION,
        'A'
    );
END;
/


--Procedimiento para actualizar categoria
CREATE OR REPLACE PROCEDURE SP_UPD_CATEGORIA (
    P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE,
    P_NOMBRE_CATEGORIA IN CATEGORIAS.NOMBRE_CATEGORIA%TYPE,
    P_DESCRIPCION IN CATEGORIAS.DESCRIPCION%TYPE,
    P_ESTADO IN CATEGORIAS.ESTADO%TYPE
)
AS
BEGIN
    UPDATE CATEGORIAS
    SET NOMBRE_CATEGORIA = P_NOMBRE_CATEGORIA,
        DESCRIPCION = P_DESCRIPCION,
        ESTADO = P_ESTADO
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
END;
/


--Procedimiento para eliminar categoria logicamente(cambiar de estado a "I")
--No se borra fisicamente por que puede tener productos relacionados
CREATE OR REPLACE PROCEDURE SP_DEL_CATEGORIA (
    P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE
)
AS
BEGIN
    UPDATE CATEGORIAS
    SET ESTADO = 'I'
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
END;
/


--verificar que se crearon los procedimientos:
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_CATEGORIA',
    'SP_UPD_CATEGORIA',
    'SP_DEL_CATEGORIA'
)
ORDER BY OBJECT_NAME;


--Probamos los procedimientos

--Insertar
EXECUTE SP_INS_CATEGORIA('LIMPIEZA', 'Productos de limpieza para oficina');

COMMIT;

SELECT * FROM CATEGORIAS
ORDER BY ID_CATEGORIA;


--Actualizar
EXECUTE SP_UPD_CATEGORIA(3, 'LIMPIEZA Y ASEO', 'Productos de limpieza y aseo general', 'A');

COMMIT;

SELECT * FROM CATEGORIAS
ORDER BY ID_CATEGORIA;


--"Eliminar"
EXECUTE SP_DEL_CATEGORIA(3);

COMMIT;

SELECT * FROM CATEGORIAS
ORDER BY ID_CATEGORIA;




--PRODUCTOS

--Procedimiento para insertar producto
CREATE OR REPLACE PROCEDURE SP_INS_PRODUCTO (
    P_ID_CATEGORIA IN PRODUCTOS.ID_CATEGORIA%TYPE,
    P_ID_PROVEEDOR IN PRODUCTOS.ID_PROVEEDOR%TYPE,
    P_NOMBRE_PRODUCTO IN PRODUCTOS.NOMBRE_PRODUCTO%TYPE,
    P_DESCRIPCION IN PRODUCTOS.DESCRIPCION%TYPE,
    P_PRECIO_COMPRA IN PRODUCTOS.PRECIO_COMPRA%TYPE,
    P_PRECIO_VENTA IN PRODUCTOS.PRECIO_VENTA%TYPE,
    P_STOCK IN PRODUCTOS.STOCK%TYPE,
    P_STOCK_MINIMO IN PRODUCTOS.STOCK_MINIMO%TYPE
)
AS
BEGIN
    IF P_PRECIO_VENTA < P_PRECIO_COMPRA THEN
        RAISE_APPLICATION_ERROR(-20010, 'El precio de venta no puede ser menor que el precio de compra.');
    END IF;

    INSERT INTO PRODUCTOS (
        ID_PRODUCTO,
        ID_CATEGORIA,
        ID_PROVEEDOR,
        NOMBRE_PRODUCTO,
        DESCRIPCION,
        PRECIO_COMPRA,
        PRECIO_VENTA,
        STOCK,
        STOCK_MINIMO,
        ESTADO
    )
    VALUES (
        SQ_PRODUCTOS.NEXTVAL,
        P_ID_CATEGORIA,
        P_ID_PROVEEDOR,
        P_NOMBRE_PRODUCTO,
        P_DESCRIPCION,
        P_PRECIO_COMPRA,
        P_PRECIO_VENTA,
        P_STOCK,
        P_STOCK_MINIMO,
        'A'
    );
END;
/


--Procedimiento para actualizar producto
CREATE OR REPLACE PROCEDURE SP_UPD_PRODUCTO (
    P_ID_PRODUCTO IN PRODUCTOS.ID_PRODUCTO%TYPE,
    P_ID_CATEGORIA IN PRODUCTOS.ID_CATEGORIA%TYPE,
    P_ID_PROVEEDOR IN PRODUCTOS.ID_PROVEEDOR%TYPE,
    P_NOMBRE_PRODUCTO IN PRODUCTOS.NOMBRE_PRODUCTO%TYPE,
    P_DESCRIPCION IN PRODUCTOS.DESCRIPCION%TYPE,
    P_PRECIO_COMPRA IN PRODUCTOS.PRECIO_COMPRA%TYPE,
    P_PRECIO_VENTA IN PRODUCTOS.PRECIO_VENTA%TYPE,
    P_STOCK IN PRODUCTOS.STOCK%TYPE,
    P_STOCK_MINIMO IN PRODUCTOS.STOCK_MINIMO%TYPE,
    P_ESTADO IN PRODUCTOS.ESTADO%TYPE
)
AS
BEGIN
    IF P_PRECIO_VENTA < P_PRECIO_COMPRA THEN
        RAISE_APPLICATION_ERROR(-20011, 'El precio de venta no puede ser menor que el precio de compra.');
    END IF;

    UPDATE PRODUCTOS
    SET ID_CATEGORIA = P_ID_CATEGORIA,
        ID_PROVEEDOR = P_ID_PROVEEDOR,
        NOMBRE_PRODUCTO = P_NOMBRE_PRODUCTO,
        DESCRIPCION = P_DESCRIPCION,
        PRECIO_COMPRA = P_PRECIO_COMPRA,
        PRECIO_VENTA = P_PRECIO_VENTA,
        STOCK = P_STOCK,
        STOCK_MINIMO = P_STOCK_MINIMO,
        ESTADO = P_ESTADO
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
END;
/


--Procedimiento para eliminar producto lOgicamente
--No vamos a borrar el producto físicamente porque
--puede estar relacionado con ventas, compras y movimientos de inventario.
CREATE OR REPLACE PROCEDURE SP_DEL_PRODUCTO (
    P_ID_PRODUCTO IN PRODUCTOS.ID_PRODUCTO%TYPE
)
AS
BEGIN
    UPDATE PRODUCTOS
    SET ESTADO = 'I'
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
END;
/

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_PRODUCTO',
    'SP_UPD_PRODUCTO',
    'SP_DEL_PRODUCTO'
)
ORDER BY OBJECT_NAME;


--LOS PROBAMOS

--INSERTAR
BEGIN
    SP_INS_PRODUCTO(
        P_ID_CATEGORIA => 1,
        P_ID_PROVEEDOR => 1,
        P_NOMBRE_PRODUCTO => 'TECLADO USB',
        P_DESCRIPCION => 'Teclado basico con conexion USB',
        P_PRECIO_COMPRA => 3500,
        P_PRECIO_VENTA => 6500,
        P_STOCK => 15,
        P_STOCK_MINIMO => 5
    );
END;
/

COMMIT;

SELECT
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    PRECIO_COMPRA,
    PRECIO_VENTA,
    STOCK,
    STOCK_MINIMO,
    ESTADO
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;


--Actualizar
BEGIN
    SP_UPD_PRODUCTO(
        P_ID_PRODUCTO => 3,
        P_ID_CATEGORIA => 1,
        P_ID_PROVEEDOR => 1,
        P_NOMBRE_PRODUCTO => 'TECLADO MECANICO BASICO',
        P_DESCRIPCION => 'Teclado mecanico basico con conexion USB',
        P_PRECIO_COMPRA => 5000,
        P_PRECIO_VENTA => 9000,
        P_STOCK => 15,
        P_STOCK_MINIMO => 5,
        P_ESTADO => 'A'
    );
END;
/

COMMIT;

SELECT
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    DESCRIPCION,
    PRECIO_COMPRA,
    PRECIO_VENTA,
    STOCK,
    STOCK_MINIMO,
    ESTADO
FROM PRODUCTOS
WHERE ID_PRODUCTO = 3;


--"ELIMINAR"
BEGIN
    SP_DEL_PRODUCTO(
        P_ID_PRODUCTO => 3
    );
END;
/

COMMIT;

SELECT
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK,
    ESTADO
FROM PRODUCTOS
WHERE ID_PRODUCTO = 3;




--procedimientos para ventas

--insertar
CREATE OR REPLACE PROCEDURE SP_INS_VENTA (
    P_ID_CLIENTE IN VENTAS.ID_CLIENTE%TYPE,
    P_ID_USUARIO IN VENTAS.ID_USUARIO%TYPE,
    P_ID_VENTA OUT VENTAS.ID_VENTA%TYPE
)
AS
BEGIN
    P_ID_VENTA := SQ_VENTAS.NEXTVAL;

    INSERT INTO VENTAS (
        ID_VENTA,
        ID_CLIENTE,
        ID_USUARIO,
        TOTAL,
        ESTADO
    )
    VALUES (
        P_ID_VENTA,
        P_ID_CLIENTE,
        P_ID_USUARIO,
        0,
        'REGISTRADA'
    );
END;
/

--El de detalle de venta
CREATE OR REPLACE PROCEDURE SP_INS_DETALLE_VENTA (
    P_ID_VENTA IN DETALLE_VENTAS.ID_VENTA%TYPE,
    P_ID_PRODUCTO IN DETALLE_VENTAS.ID_PRODUCTO%TYPE,
    P_CANTIDAD IN DETALLE_VENTAS.CANTIDAD%TYPE
)
AS
BEGIN
    INSERT INTO DETALLE_VENTAS (
        ID_DETALLE_VENTA,
        ID_VENTA,
        ID_PRODUCTO,
        CANTIDAD
    )
    VALUES (
        SQ_DETALLE_VENTAS.NEXTVAL,
        P_ID_VENTA,
        P_ID_PRODUCTO,
        P_CANTIDAD
    );
END;
/


SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_VENTA',
    'SP_INS_DETALLE_VENTA'
)
ORDER BY OBJECT_NAME;



--Probar venta usando los procedimientos

--crear la venta
SET SERVEROUTPUT ON;

DECLARE
    V_ID_VENTA NUMBER;
BEGIN
    SP_INS_VENTA(
        P_ID_CLIENTE => 2,
        P_ID_USUARIO => 2,
        P_ID_VENTA => V_ID_VENTA
    );

    SP_INS_DETALLE_VENTA(
        P_ID_VENTA => V_ID_VENTA,
        P_ID_PRODUCTO => 1,
        P_CANTIDAD => 2
    );

    DBMS_OUTPUT.PUT_LINE('Venta creada correctamente. ID_VENTA: ' || V_ID_VENTA);
END;
/

COMMIT;

--verificar venta
SELECT
    ID_VENTA,
    ID_CLIENTE,
    ID_USUARIO,
    TOTAL,
    ESTADO
FROM VENTAS
ORDER BY ID_VENTA;

--verificar detalle de venta
SELECT *
FROM VW_VENTAS_DETALLE
ORDER BY ID_VENTA;

--verificar stock
SELECT 
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;

--verificar movimiento automatico
SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;


--procedimientos para anular ventas y compras:

--Procedimiento para anular venta
--Cambia VENTAS.ESTADO a ANULADA.
--el stock de los productos vendidos.
--Registra movimiento de inventario tipo ENTRADA.

CREATE OR REPLACE PROCEDURE SP_DEL_VENTA (
    P_ID_VENTA IN VENTAS.ID_VENTA%TYPE
)
AS
    V_ESTADO VENTAS.ESTADO%TYPE;
    V_ID_USUARIO VENTAS.ID_USUARIO%TYPE;
    V_STOCK_ANTERIOR PRODUCTOS.STOCK%TYPE;
BEGIN
    SELECT ESTADO, ID_USUARIO
    INTO V_ESTADO, V_ID_USUARIO
    FROM VENTAS
    WHERE ID_VENTA = P_ID_VENTA;

    IF V_ESTADO = 'ANULADA' THEN
        RAISE_APPLICATION_ERROR(-20020, 'La venta ya se encuentra anulada.');
    END IF;

    FOR DET IN (
        SELECT ID_PRODUCTO, CANTIDAD
        FROM DETALLE_VENTAS
        WHERE ID_VENTA = P_ID_VENTA
    ) LOOP

        SELECT STOCK
        INTO V_STOCK_ANTERIOR
        FROM PRODUCTOS
        WHERE ID_PRODUCTO = DET.ID_PRODUCTO;

        UPDATE PRODUCTOS
        SET STOCK = STOCK + DET.CANTIDAD
        WHERE ID_PRODUCTO = DET.ID_PRODUCTO;

        INSERT INTO MOVIMIENTOS_INVENTARIO (
            ID_MOVIMIENTO,
            ID_PRODUCTO,
            ID_USUARIO,
            TIPO_MOVIMIENTO,
            CANTIDAD,
            STOCK_ANTERIOR,
            STOCK_NUEVO,
            DESCRIPCION,
            ID_VENTA
        )
        VALUES (
            SQ_MOVIMIENTOS_INVENTARIO.NEXTVAL,
            DET.ID_PRODUCTO,
            V_ID_USUARIO,
            'ENTRADA',
            DET.CANTIDAD,
            V_STOCK_ANTERIOR,
            V_STOCK_ANTERIOR + DET.CANTIDAD,
            'Entrada por anulacion de venta',
            P_ID_VENTA
        );

    END LOOP;

    UPDATE VENTAS
    SET ESTADO = 'ANULADA'
    WHERE ID_VENTA = P_ID_VENTA;
END;
/



--Procedimiento para anular compra
--Cambia COMPRAS.ESTADO a ANULADA.
--Descuenta del stock lo que se había comprado.
--Registra movimiento de inventario tipo SALIDA.
CREATE OR REPLACE PROCEDURE SP_DEL_COMPRA (
    P_ID_COMPRA IN COMPRAS.ID_COMPRA%TYPE
)
AS
    V_ESTADO COMPRAS.ESTADO%TYPE;
    V_ID_USUARIO COMPRAS.ID_USUARIO%TYPE;
    V_STOCK_ANTERIOR PRODUCTOS.STOCK%TYPE;
BEGIN
    SELECT ESTADO, ID_USUARIO
    INTO V_ESTADO, V_ID_USUARIO
    FROM COMPRAS
    WHERE ID_COMPRA = P_ID_COMPRA;

    IF V_ESTADO = 'ANULADA' THEN
        RAISE_APPLICATION_ERROR(-20021, 'La compra ya se encuentra anulada.');
    END IF;

    FOR DET IN (
        SELECT ID_PRODUCTO, CANTIDAD
        FROM DETALLE_COMPRAS
        WHERE ID_COMPRA = P_ID_COMPRA
    ) LOOP

        SELECT STOCK
        INTO V_STOCK_ANTERIOR
        FROM PRODUCTOS
        WHERE ID_PRODUCTO = DET.ID_PRODUCTO;

        IF V_STOCK_ANTERIOR < DET.CANTIDAD THEN
            RAISE_APPLICATION_ERROR(-20022, 'No hay stock suficiente para anular la compra.');
        END IF;

        UPDATE PRODUCTOS
        SET STOCK = STOCK - DET.CANTIDAD
        WHERE ID_PRODUCTO = DET.ID_PRODUCTO;

        INSERT INTO MOVIMIENTOS_INVENTARIO (
            ID_MOVIMIENTO,
            ID_PRODUCTO,
            ID_USUARIO,
            TIPO_MOVIMIENTO,
            CANTIDAD,
            STOCK_ANTERIOR,
            STOCK_NUEVO,
            DESCRIPCION,
            ID_COMPRA
        )
        VALUES (
            SQ_MOVIMIENTOS_INVENTARIO.NEXTVAL,
            DET.ID_PRODUCTO,
            V_ID_USUARIO,
            'SALIDA',
            DET.CANTIDAD,
            V_STOCK_ANTERIOR,
            V_STOCK_ANTERIOR - DET.CANTIDAD,
            'Salida por anulacion de compra',
            P_ID_COMPRA
        );

    END LOOP;

    UPDATE COMPRAS
    SET ESTADO = 'ANULADA'
    WHERE ID_COMPRA = P_ID_COMPRA;
END;
/

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_DEL_VENTA',
    'SP_DEL_COMPRA'
)
ORDER BY OBJECT_NAME;


--Prueba anulando la venta 3
BEGIN
    SP_DEL_VENTA(3);
END;
/

COMMIT;

--revisar que salga anulada
SELECT
    ID_VENTA,
    TOTAL,
    ESTADO
FROM VENTAS
WHERE ID_VENTA = 3;

--revisar stock
SELECT 
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;

--revisar movimiento
SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;



--Probamos anular la compra 6
BEGIN
    SP_DEL_COMPRA(6);
END;
/

COMMIT;

--Ver que salga anulada
SELECT
    ID_COMPRA,
    TOTAL,
    ESTADO
FROM COMPRAS
WHERE ID_COMPRA = 6;

--ver stock
SELECT 
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;

--revisar movimientos
SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;



--Procedimientos para los Clientes

--Insertar cliente
CREATE OR REPLACE PROCEDURE SP_INS_CLIENTE (
    P_NOMBRE_CLIENTE IN CLIENTES.NOMBRE_CLIENTE%TYPE,
    P_CEDULA IN CLIENTES.CEDULA%TYPE,
    P_TELEFONO IN CLIENTES.TELEFONO%TYPE,
    P_CORREO IN CLIENTES.CORREO%TYPE,
    P_DIRECCION IN CLIENTES.DIRECCION%TYPE
)
AS
BEGIN
    INSERT INTO CLIENTES (
        ID_CLIENTE,
        NOMBRE_CLIENTE,
        CEDULA,
        TELEFONO,
        CORREO,
        DIRECCION,
        ESTADO
    )
    VALUES (
        SQ_CLIENTES.NEXTVAL,
        P_NOMBRE_CLIENTE,
        P_CEDULA,
        P_TELEFONO,
        P_CORREO,
        P_DIRECCION,
        'A'
    );
END;
/


--Actualizar cliente
CREATE OR REPLACE PROCEDURE SP_UPD_CLIENTE (
    P_ID_CLIENTE IN CLIENTES.ID_CLIENTE%TYPE,
    P_NOMBRE_CLIENTE IN CLIENTES.NOMBRE_CLIENTE%TYPE,
    P_CEDULA IN CLIENTES.CEDULA%TYPE,
    P_TELEFONO IN CLIENTES.TELEFONO%TYPE,
    P_CORREO IN CLIENTES.CORREO%TYPE,
    P_DIRECCION IN CLIENTES.DIRECCION%TYPE,
    P_ESTADO IN CLIENTES.ESTADO%TYPE
)
AS
BEGIN
    UPDATE CLIENTES
    SET NOMBRE_CLIENTE = P_NOMBRE_CLIENTE,
        CEDULA = P_CEDULA,
        TELEFONO = P_TELEFONO,
        CORREO = P_CORREO,
        DIRECCION = P_DIRECCION,
        ESTADO = P_ESTADO
    WHERE ID_CLIENTE = P_ID_CLIENTE;
END;
/


--"Eliminar cliente"
CREATE OR REPLACE PROCEDURE SP_DEL_CLIENTE (
    P_ID_CLIENTE IN CLIENTES.ID_CLIENTE%TYPE
)
AS
BEGIN
    UPDATE CLIENTES
    SET ESTADO = 'I'
    WHERE ID_CLIENTE = P_ID_CLIENTE;
END;
/

--revisar que se crearan:
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_CLIENTE',
    'SP_UPD_CLIENTE',
    'SP_DEL_CLIENTE'
)
ORDER BY OBJECT_NAME;


--Pruebas de esos procedimientos:

--Insertar
BEGIN
    SP_INS_CLIENTE(
        P_NOMBRE_CLIENTE => 'Carlos Mendez',
        P_CEDULA => '222222222',
        P_TELEFONO => '8888-4444',
        P_CORREO => 'carlos@correo.com',
        P_DIRECCION => 'Alajuela, Costa Rica'
    );
END;
/

COMMIT;

SELECT *
FROM CLIENTES
ORDER BY ID_CLIENTE;


--Actualizar
BEGIN
    SP_UPD_CLIENTE(
        P_ID_CLIENTE => 3,
        P_NOMBRE_CLIENTE => 'Carlos Mendez Vargas',
        P_CEDULA => '222222222',
        P_TELEFONO => '8888-5555',
        P_CORREO => 'carlos.mendez@correo.com',
        P_DIRECCION => 'Alajuela centro, Costa Rica',
        P_ESTADO => 'A'
    );
END;
/

COMMIT;


--"Eliminar"
BEGIN
    SP_DEL_CLIENTE(
        P_ID_CLIENTE => 3
    );
END;
/

COMMIT;


--Revision
SELECT
    ID_CLIENTE,
    NOMBRE_CLIENTE,
    CEDULA,
    TELEFONO,
    CORREO,
    ESTADO
FROM CLIENTES
ORDER BY ID_CLIENTE;





--Procedimientos para los proveedores

--Insertar proveedor
CREATE OR REPLACE PROCEDURE SP_INS_PROVEEDOR (
    P_NOMBRE_PROVEEDOR IN PROVEEDORES.NOMBRE_PROVEEDOR%TYPE,
    P_TELEFONO IN PROVEEDORES.TELEFONO%TYPE,
    P_CORREO IN PROVEEDORES.CORREO%TYPE,
    P_DIRECCION IN PROVEEDORES.DIRECCION%TYPE
)
AS
BEGIN
    INSERT INTO PROVEEDORES (
        ID_PROVEEDOR,
        NOMBRE_PROVEEDOR,
        TELEFONO,
        CORREO,
        DIRECCION,
        ESTADO
    )
    VALUES (
        SQ_PROVEEDORES.NEXTVAL,
        P_NOMBRE_PROVEEDOR,
        P_TELEFONO,
        P_CORREO,
        P_DIRECCION,
        'A'
    );
END;
/



--Actualizar proveedor
CREATE OR REPLACE PROCEDURE SP_UPD_PROVEEDOR (
    P_ID_PROVEEDOR IN PROVEEDORES.ID_PROVEEDOR%TYPE,
    P_NOMBRE_PROVEEDOR IN PROVEEDORES.NOMBRE_PROVEEDOR%TYPE,
    P_TELEFONO IN PROVEEDORES.TELEFONO%TYPE,
    P_CORREO IN PROVEEDORES.CORREO%TYPE,
    P_DIRECCION IN PROVEEDORES.DIRECCION%TYPE,
    P_ESTADO IN PROVEEDORES.ESTADO%TYPE
)
AS
BEGIN
    UPDATE PROVEEDORES
    SET NOMBRE_PROVEEDOR = P_NOMBRE_PROVEEDOR,
        TELEFONO = P_TELEFONO,
        CORREO = P_CORREO,
        DIRECCION = P_DIRECCION,
        ESTADO = P_ESTADO
    WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
END;
/




--"Eliminar proveedor"
CREATE OR REPLACE PROCEDURE SP_DEL_PROVEEDOR (
    P_ID_PROVEEDOR IN PROVEEDORES.ID_PROVEEDOR%TYPE
)
AS
BEGIN
    UPDATE PROVEEDORES
    SET ESTADO = 'I'
    WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
END;
/


--Revisar que existan
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_PROVEEDOR',
    'SP_UPD_PROVEEDOR',
    'SP_DEL_PROVEEDOR'
)
ORDER BY OBJECT_NAME;


--Pruebas:

--Insertar
BEGIN
    SP_INS_PROVEEDOR(
        P_NOMBRE_PROVEEDOR => 'Suministros Globales',
        P_TELEFONO => '2222-7777',
        P_CORREO => 'globales@proveedores.com',
        P_DIRECCION => 'San Pedro, Costa Rica'
    );
END;
/

COMMIT;

SELECT *
FROM PROVEEDORES
ORDER BY ID_PROVEEDOR;

--Actualizar
BEGIN
    SP_UPD_PROVEEDOR(
        P_ID_PROVEEDOR => 3,
        P_NOMBRE_PROVEEDOR => 'Suministros Globales CR',
        P_TELEFONO => '2222-8888',
        P_CORREO => 'globalescr@proveedores.com',
        P_DIRECCION => 'San Pedro, Montes de Oca, Costa Rica',
        P_ESTADO => 'A'
    );
END;
/

COMMIT;

SELECT
    ID_PROVEEDOR,
    NOMBRE_PROVEEDOR,
    TELEFONO,
    CORREO,
    DIRECCION,
    ESTADO
FROM PROVEEDORES
ORDER BY ID_PROVEEDOR;


--Eliminar
BEGIN
    SP_DEL_PROVEEDOR(
        P_ID_PROVEEDOR => 3
    );
END;
/

COMMIT;

SELECT
    ID_PROVEEDOR,
    NOMBRE_PROVEEDOR,
    TELEFONO,
    CORREO,
    ESTADO
FROM PROVEEDORES
ORDER BY ID_PROVEEDOR;






--Crear procedimientos para USUARIOS

--Insertar Usuario
CREATE OR REPLACE PROCEDURE SP_INS_USUARIO (
    P_ID_ROL IN USUARIOS.ID_ROL%TYPE,
    P_NOMBRE IN USUARIOS.NOMBRE%TYPE,
    P_CORREO IN USUARIOS.CORREO%TYPE,
    P_PASSWORD IN USUARIOS.PASSWORD%TYPE
)
AS
BEGIN
    INSERT INTO USUARIOS (
        ID_USUARIO,
        ID_ROL,
        NOMBRE,
        CORREO,
        PASSWORD,
        ESTADO
    )
    VALUES (
        SQ_USUARIOS.NEXTVAL,
        P_ID_ROL,
        P_NOMBRE,
        P_CORREO,
        P_PASSWORD,
        'A'
    );
END;
/


--Actualizar usuario
CREATE OR REPLACE PROCEDURE SP_UPD_USUARIO (
    P_ID_USUARIO IN USUARIOS.ID_USUARIO%TYPE,
    P_ID_ROL IN USUARIOS.ID_ROL%TYPE,
    P_NOMBRE IN USUARIOS.NOMBRE%TYPE,
    P_CORREO IN USUARIOS.CORREO%TYPE,
    P_PASSWORD IN USUARIOS.PASSWORD%TYPE,
    P_ESTADO IN USUARIOS.ESTADO%TYPE
)
AS
BEGIN
    UPDATE USUARIOS
    SET ID_ROL = P_ID_ROL,
        NOMBRE = P_NOMBRE,
        CORREO = P_CORREO,
        PASSWORD = P_PASSWORD,
        ESTADO = P_ESTADO
    WHERE ID_USUARIO = P_ID_USUARIO;
END;
/



--"Eliminar usuario"
CREATE OR REPLACE PROCEDURE SP_DEL_USUARIO (
    P_ID_USUARIO IN USUARIOS.ID_USUARIO%TYPE
)
AS
BEGIN
    UPDATE USUARIOS
    SET ESTADO = 'I'
    WHERE ID_USUARIO = P_ID_USUARIO;
END;
/



--Revisar que se crearon
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_USUARIO',
    'SP_UPD_USUARIO',
    'SP_DEL_USUARIO'
)
ORDER BY OBJECT_NAME;


--Pruebas de los procedimientos de usuarios

--Insertar
BEGIN
    SP_INS_USUARIO(
        P_ID_ROL => 2,
        P_NOMBRE => 'Usuario Prueba',
        P_CORREO => 'prueba@inventario.com',
        P_PASSWORD => '123456'
    );
END;
/

COMMIT;

SELECT
    U.ID_USUARIO,
    U.NOMBRE,
    U.CORREO,
    R.NOMBRE_ROL,
    U.ESTADO,
    U.FECHA_REGISTRO
FROM USUARIOS U
INNER JOIN ROLES R ON U.ID_ROL = R.ID_ROL
ORDER BY U.ID_USUARIO;

--Actualizar
BEGIN
    SP_UPD_USUARIO(
        P_ID_USUARIO => 3,
        P_ID_ROL => 2,
        P_NOMBRE => 'Usuario Prueba Actualizado',
        P_CORREO => 'prueba.actualizado@inventario.com',
        P_PASSWORD => '123456',
        P_ESTADO => 'A'
    );
END;
/

COMMIT;


--"Eliminar"
BEGIN
    SP_DEL_USUARIO(
        P_ID_USUARIO => 3
    );
END;
/

COMMIT;

SELECT
    U.ID_USUARIO,
    U.NOMBRE,
    U.CORREO,
    R.NOMBRE_ROL,
    U.ESTADO
FROM USUARIOS U
INNER JOIN ROLES R ON U.ID_ROL = R.ID_ROL
ORDER BY U.ID_USUARIO;





--Procedimiento de compras

--Insertar compra
CREATE OR REPLACE PROCEDURE SP_INS_COMPRA (
    P_ID_PROVEEDOR IN COMPRAS.ID_PROVEEDOR%TYPE,
    P_ID_USUARIO IN COMPRAS.ID_USUARIO%TYPE,
    P_ID_COMPRA OUT COMPRAS.ID_COMPRA%TYPE
)
AS
BEGIN
    P_ID_COMPRA := SQ_COMPRAS.NEXTVAL;

    INSERT INTO COMPRAS (
        ID_COMPRA,
        ID_PROVEEDOR,
        ID_USUARIO,
        TOTAL,
        ESTADO
    )
    VALUES (
        P_ID_COMPRA,
        P_ID_PROVEEDOR,
        P_ID_USUARIO,
        0,
        'REGISTRADA'
    );
END;
/


--Insetar detalle compra
CREATE OR REPLACE PROCEDURE SP_INS_DETALLE_COMPRA (
    P_ID_COMPRA IN DETALLE_COMPRAS.ID_COMPRA%TYPE,
    P_ID_PRODUCTO IN DETALLE_COMPRAS.ID_PRODUCTO%TYPE,
    P_CANTIDAD IN DETALLE_COMPRAS.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO IN DETALLE_COMPRAS.PRECIO_UNITARIO%TYPE
)
AS
BEGIN
    INSERT INTO DETALLE_COMPRAS (
        ID_DETALLE_COMPRA,
        ID_COMPRA,
        ID_PRODUCTO,
        CANTIDAD,
        PRECIO_UNITARIO,
        SUBTOTAL
    )
    VALUES (
        SQ_DETALLE_COMPRAS.NEXTVAL,
        P_ID_COMPRA,
        P_ID_PRODUCTO,
        P_CANTIDAD,
        P_PRECIO_UNITARIO,
        0
    );
END;
/


--Revisar
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'SP_INS_COMPRA',
    'SP_INS_DETALLE_COMPRA',
    'SP_DEL_COMPRA'
)
ORDER BY OBJECT_NAME;



--Pruebas
SET SERVEROUTPUT ON;

DECLARE
    V_ID_COMPRA NUMBER;
BEGIN
    SP_INS_COMPRA(
        P_ID_PROVEEDOR => 1,
        P_ID_USUARIO => 1,
        P_ID_COMPRA => V_ID_COMPRA
    );

    SP_INS_DETALLE_COMPRA(
        P_ID_COMPRA => V_ID_COMPRA,
        P_ID_PRODUCTO => 1,
        P_CANTIDAD => 2,
        P_PRECIO_UNITARIO => 4500
    );

    DBMS_OUTPUT.PUT_LINE('Compra creada correctamente. ID_COMPRA: ' || V_ID_COMPRA);
END;
/

COMMIT;

--Revisar stock
SELECT 
    ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    STOCK
FROM PRODUCTOS
ORDER BY ID_PRODUCTO;


--Ver compra y movimiento
SELECT *
FROM VW_COMPRAS_DETALLE
ORDER BY ID_COMPRA;

SELECT
    M.ID_MOVIMIENTO,
    P.NOMBRE_PRODUCTO,
    U.NOMBRE AS USUARIO,
    M.TIPO_MOVIMIENTO,
    M.CANTIDAD,
    M.STOCK_ANTERIOR,
    M.STOCK_NUEVO,
    M.DESCRIPCION
FROM MOVIMIENTOS_INVENTARIO M
INNER JOIN PRODUCTOS P ON M.ID_PRODUCTO = P.ID_PRODUCTO
INNER JOIN USUARIOS U ON M.ID_USUARIO = U.ID_USUARIO
ORDER BY M.ID_MOVIMIENTO;


--VER TODAS LAS TABLAS
SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;

--VER TODAS LAS SECUENCIAS
SELECT SEQUENCE_NAME
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME LIKE 'SQ_%'
ORDER BY SEQUENCE_NAME;

--VER TODOS LOS TRIGGERS
SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN (
    'TRG_AI_DETALLE_COMPRAS',
    'TRG_AI_DETALLE_VENTAS',
    'TRG_BI_DETALLE_COMPRAS',
    'TRG_BI_DETALLE_VENTAS'
)
ORDER BY TRIGGER_NAME;


--VER TODAS LAS VISTAS - VIEWS
SELECT VIEW_NAME
FROM USER_VIEWS
WHERE VIEW_NAME LIKE 'VW_%'
ORDER BY VIEW_NAME;


--VER TODOS LOS PROCECDIEMIENTOS ALMACENADOS (SP)
SELECT
    OBJECT_NAME,
    OBJECT_TYPE,
    STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'PROCEDURE'
AND OBJECT_NAME LIKE 'SP_%'
ORDER BY OBJECT_NAME;


--VER QUE NO HAYAN OBJETOS CON ALGUN ERROR
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE STATUS <> 'VALID'
ORDER BY OBJECT_TYPE, OBJECT_NAME;


--indices:
-- Indices para relaciones de PRODUCTOS
CREATE INDEX IDX_PRODUCTOS_CATEGORIA
ON PRODUCTOS(ID_CATEGORIA);

CREATE INDEX IDX_PRODUCTOS_PROVEEDOR
ON PRODUCTOS(ID_PROVEEDOR);

-- Indices para relaciones de VENTAS
CREATE INDEX IDX_VENTAS_CLIENTE
ON VENTAS(ID_CLIENTE);

CREATE INDEX IDX_VENTAS_USUARIO
ON VENTAS(ID_USUARIO);

CREATE INDEX IDX_DETALLE_VENTAS_VENTA
ON DETALLE_VENTAS(ID_VENTA);

CREATE INDEX IDX_DETALLE_VENTAS_PRODUCTO
ON DETALLE_VENTAS(ID_PRODUCTO);

-- Indices para relaciones de COMPRAS
CREATE INDEX IDX_COMPRAS_PROVEEDOR
ON COMPRAS(ID_PROVEEDOR);

CREATE INDEX IDX_COMPRAS_USUARIO
ON COMPRAS(ID_USUARIO);

CREATE INDEX IDX_DETALLE_COMPRAS_COMPRA
ON DETALLE_COMPRAS(ID_COMPRA);

CREATE INDEX IDX_DETALLE_COMPRAS_PRODUCTO
ON DETALLE_COMPRAS(ID_PRODUCTO);

-- Indices para movimientos de inventario
CREATE INDEX IDX_MOV_INV_PRODUCTO
ON MOVIMIENTOS_INVENTARIO(ID_PRODUCTO);

CREATE INDEX IDX_MOV_INV_USUARIO
ON MOVIMIENTOS_INVENTARIO(ID_USUARIO);

-- Indices para busquedas y reportes por fechas
CREATE INDEX IDX_VENTAS_FECHA
ON VENTAS(FECHA_VENTA);

CREATE INDEX IDX_COMPRAS_FECHA
ON COMPRAS(FECHA_COMPRA);

CREATE INDEX IDX_MOV_INV_FECHA
ON MOVIMIENTOS_INVENTARIO(FECHA_MOVIMIENTO);

--Ver todos los indices
SELECT
    INDEX_NAME,
    TABLE_NAME,
    STATUS
FROM USER_INDEXES
WHERE INDEX_NAME LIKE 'IDX_%'
ORDER BY TABLE_NAME, INDEX_NAME;



--CURSOR PARA VER EL INVENTARIO GENERAL
CREATE OR REPLACE PROCEDURE SP_CURSOR_INVENTARIO_GENERAL (
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            ID_PRODUCTO,
            NOMBRE_PRODUCTO,
            NOMBRE_CATEGORIA,
            NOMBRE_PROVEEDOR,
            PRECIO_COMPRA,
            PRECIO_VENTA,
            STOCK,
            STOCK_MINIMO,
            ESTADO
        FROM VW_INVENTARIO_GENERAL
        ORDER BY ID_PRODUCTO;
END;
/

--PROBARLO:
VARIABLE RC REFCURSOR;

EXECUTE SP_CURSOR_INVENTARIO_GENERAL(:RC);

PRINT RC;





--OTRO CURSOR:

--CURSOR PARA EL STOCK BAJO

CREATE OR REPLACE PROCEDURE SP_CURSOR_STOCK_BAJO (
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT
            ID_PRODUCTO,
            NOMBRE_PRODUCTO,
            NOMBRE_CATEGORIA,
            NOMBRE_PROVEEDOR,
            STOCK,
            STOCK_MINIMO,
            ESTADO
        FROM VW_PRODUCTOS_STOCK_BAJO
        ORDER BY STOCK ASC;
END;
/

--REVISAR QUE SE CREARA
SELECT
    OBJECT_NAME,
    OBJECT_TYPE,
    STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'SP_CURSOR_STOCK_BAJO';

--probar el cursor:
VARIABLE RC REFCURSOR;

EXECUTE SP_CURSOR_STOCK_BAJO(:RC);

PRINT RC;


--Llaves primarias y foráneas del proyecto
SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    TABLE_NAME,
    STATUS
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE IN ('P', 'R')
AND TABLE_NAME IN (
    'CATEGORIAS',
    'CLIENTES',
    'COMPRAS',
    'DETALLE_COMPRAS',
    'DETALLE_VENTAS',
    'MOVIMIENTOS_INVENTARIO',
    'PRODUCTOS',
    'PROVEEDORES',
    'ROLES',
    'USUARIOS',
    'VENTAS'
)
ORDER BY TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;

--hashear

UPDATE USUARIOS
SET PASSWORD = '\$2y\$12\$FIQFtyZq4j11scjTYUpMEeYSxucGyNXn0y5eyAcG5bx3MFl6Cv3qS'
WHERE CORREO IN (
    'admin@inventario.com',
    'vendedor@inventario.com',
    'prueba.actualizado@inventario.com'
);

COMMIT;

--luego

UPDATE USUARIOS
SET PASSWORD = REPLACE(PASSWORD, '\$', '$')
WHERE PASSWORD LIKE '\$2y\$%';

COMMIT;

--revisar
SELECT
    ID_USUARIO,
    NOMBRE,
    CORREO,
    SUBSTR(PASSWORD, 1, 10) || '...' AS PASSWORD_MUESTRA,
    LENGTH(PASSWORD) AS LARGO_PASSWORD,
    CASE
        WHEN PASSWORD LIKE '$2y$%' THEN 'HASHEADA'
        WHEN PASSWORD LIKE '$2a$%' THEN 'HASHEADA'
        WHEN PASSWORD LIKE '$2b$%' THEN 'HASHEADA'
        ELSE 'NO HASHEADA'
    END AS ESTADO_PASSWORD
FROM USUARIOS
ORDER BY ID_USUARIO;

SELECT
    U.ID_USUARIO,
    U.NOMBRE,
    U.CORREO,
    R.NOMBRE_ROL,
    '********' AS PASSWORD,
    U.ESTADO,
    U.FECHA_REGISTRO
FROM USUARIOS U
INNER JOIN ROLES R ON U.ID_ROL = R.ID_ROL
WHERE U.CORREO IN (
    'admin@inventario.com',
    'vendedor@inventario.com'
)
ORDER BY U.ID_USUARIO;